In [1]:
import pandas as pd

In [2]:
d=pd.read_csv("pbl.csv")

In [3]:
d

,userId,movieId,rating,timestamp,movie_title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,964982224,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
...,...,...,...,...,...,...
100245,610,166534,4.0,1493848402,Split (2017),Drama|Horror|Thriller
100246,610,168248,5.0,1493850091,John Wick: Chapter Two (2017),Action|Crime|Thriller
100247,610,168250,5.0,1494273047,Get Out (2017),Horror
100248,610,168252,5.0,1493846352,Logan (2017),Action|Sci-Fi
100249,610,170875,3.0,1493846415,The Fate of the Furious (2017),Action|Crime|Drama|Thriller

In [4]:
df=pd.DataFrame(d)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100250 entries, 0 to 100249
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   userId       100250 non-null  int64
 1   movieId      100250 non-null  int64
 2   rating       100250 non-null  float64
 3   timestamp    100250 non-null  int64
 4   movie_title  100250 non-null  object
 5   genres       100250 non-null  object
dtypes: float64(1), int64(3), object(2)
memory usage: 4.6+ MB

In [6]:
df.describe()

              userId        movieId         rating     timestamp
count  100250.000000  100250.000000  100250.000000  1.002500e+05
mean      325.973566   19122.092489       3.501606  1.204787e+09
std       182.520792   35260.139972       1.041904  2.161079e+08
min         1.000000       1.000000       0.500000  8.281246e+08
25%       177.000000    1198.000000       3.000000  1.014822e+09
50%       325.000000    2973.000000       3.500000  1.182911e+09
75%       477.000000    7458.000000       4.000000  1.435944e+09
max       610.000000  193609.000000       5.000000  1.537799e+09

In [7]:
df.isnull().sum()

userId         0
movieId        0
rating         0
timestamp      0
movie_title    0
genres         0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.size

601500

In [10]:
df.shape

(100250, 6)

In [11]:
df["timestamp"] = pd.to_datetime(df["timestamp"], unit="s")

In [12]:
df["hour"] = df["timestamp"].dt.hour
df["day_of_week"] = df["timestamp"].dt.dayofweek

In [13]:
df

,userId,movieId,rating,timestamp,movie_title,genres,hour,day_of_week
0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,18,6
1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance,18,6
2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller,18,6
3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,19,6
4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,18,6
...,...,...,...,...,...,...,...,...
100245,610,166534,4.0,2017-05-03 21:53:22,Split (2017),Drama|Horror|Thriller,21,2
100246,610,168248,5.0,2017-05-03 22:21:31,John Wick: Chapter Two (2017),Action|Crime|Thriller,22,2
100247,610,168250,5.0,2017-05-08 19:50:47,Get Out (2017),Horror,19,0
100248,610,168252,5.0,2017-05-03 21:19:12,Logan (2017),Action|Sci-Fi,21,2
100249,610,170875,3.0,2017-05-03 21:20:15,The Fate of the Furious (2017),Action|Crime|Drama|Thriller,21,2

In [14]:
movie_popularity = df.groupby("movieId")["rating"].count()
df["movie_rating_count"] = df["movieId"].map(movie_popularity)

In [15]:
df

,userId,movieId,rating,timestamp,movie_title,genres,hour,day_of_week,movie_rating_count
0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,18,6,215
1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance,18,6,52
2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller,18,6,102
3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,19,6,203
4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,18,6,204
...,...,...,...,...,...,...,...,...,...
100245,610,166534,4.0,2017-05-03 21:53:22,Split (2017),Drama|Horror|Thriller,21,2,6
100246,610,168248,5.0,2017-05-03 22:21:31,John Wick: Chapter Two (2017),Action|Crime|Thriller,22,2,7
100247,610,168250,5.0,2017-05-08 19:50:47,Get Out (2017),Horror,19,0,15
100248,610,168252,5.0,2017-05-03 21:19:12,Logan (2017),Action|Sci-Fi,21,2,25
100249,610,170875,3.0,2017-05-03 21:20:15,The Fate of the Furious (2017),Action|Crime|Drama|Thriller,21,2,3

In [16]:
user_activity = df.groupby("userId")["rating"].count()
df["user_rating_count"] = df["userId"].map(user_activity)

In [17]:
df

,userId,movieId,rating,timestamp,movie_title,genres,hour,day_of_week,movie_rating_count,user_rating_count
0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,18,6,215,232
1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance,18,6,52,232
2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller,18,6,102,232
3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,19,6,203,232
4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,18,6,204,232
...,...,...,...,...,...,...,...,...,...,...
100245,610,166534,4.0,2017-05-03 21:53:22,Split (2017),Drama|Horror|Thriller,21,2,6,1277
100246,610,168248,5.0,2017-05-03 22:21:31,John Wick: Chapter Two (2017),Action|Crime|Thriller,22,2,7,1277
100247,610,168250,5.0,2017-05-08 19:50:47,Get Out (2017),Horror,19,0,15,1277
100248,610,168252,5.0,2017-05-03 21:19:12,Logan (2017),Action|Sci-Fi,21,2,25,1277
100249,610,170875,3.0,2017-05-03 21:20:15,The Fate of the Furious (2017),Action|Crime|Drama|Thriller,21,2,3,1277

In [18]:
movie_avg = df.groupby("movieId")["rating"].mean()
df["movie_avg_rating"] = df["movieId"].map(movie_avg)

In [19]:
df

,userId,movieId,rating,timestamp,movie_title,genres,hour,day_of_week,movie_rating_count,user_rating_count,movie_avg_rating
0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,18,6,215,232,3.920930
1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance,18,6,52,232,3.259615
2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller,18,6,102,232,3.946078
3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,19,6,203,232,3.975369
4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,18,6,204,232,4.237745
...,...,...,...,...,...,...,...,...,...,...,...
100245,610,166534,4.0,2017-05-03 21:53:22,Split (2017),Drama|Horror|Thriller,21,2,6,1277,3.333333
100246,610,168248,5.0,2017-05-03 22:21:31,John Wick: Chapter Two (2017),Action|Crime|Thriller,22,2,7,1277,4.142857
100247,610,168250,5.0,2017-05-08 19:50:47,Get Out (2017),Horror,19,0,15,1277,3.633333
100248,610,168252,5.0,2017-05-03 21:19:12,Logan (2017),Action|Sci-Fi,21,2,25,1277,4.280000
100249,610,170875,3.0,2017-05-03 21:20:15,The Fate of the Furious (2017),Action|Crime|Drama|Thriller,21,2,3,1277,2.333333

In [20]:
import numpy as np

In [21]:
df["preference"] = np.where(df["rating"] >= 3, 1, 0)

In [22]:
df

,userId,movieId,rating,timestamp,movie_title,genres,hour,day_of_week,movie_rating_count,user_rating_count,movie_avg_rating,preference
0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,18,6,215,232,3.920930,1
1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance,18,6,52,232,3.259615,1
2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller,18,6,102,232,3.946078,1
3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,19,6,203,232,3.975369,1
4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,18,6,204,232,4.237745,1
...,...,...,...,...,...,...,...,...,...,...,...,...
100245,610,166534,4.0,2017-05-03 21:53:22,Split (2017),Drama|Horror|Thriller,21,2,6,1277,3.333333,1
100246,610,168248,5.0,2017-05-03 22:21:31,John Wick: Chapter Two (2017),Action|Crime|Thriller,22,2,7,1277,4.142857,1
100247,610,168250,5.0,2017-05-08 19:50:47,Get Out (2017),Horror,19,0,15,1277,3.633333,1
100248,610,168252,5.0,2017-05-03 21:19:12,Logan (2017),Action|Sci-Fi,21,2,25,1277,4.280000,1
100249,610,170875,3.0,2017-05-03 21:20:15,The Fate of the Furious (2017),Action|Crime|Drama|Thriller,21,2,3,1277,2.333333,1

In [23]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\acer\anaconda3\lib\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\acer\anaconda3\lib\site-packages (from scikit-learn) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in c:\users\acer\anaconda3\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\acer\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\acer\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

In [24]:
from sklearn.preprocessing import MinMaxScaler

In [25]:
scaler = MinMaxScaler()

cols_to_scale = [ "movie_rating_count", 
                 "user_rating_count", "movie_avg_rating"]

df[cols_to_scale] = scaler.fit_transform(df[cols_to_scale])

In [26]:
df["userId_encoded"] = df["userId"].astype("category").cat.codes
df["movieId_encoded"] = df["movieId"].astype("category").cat.codes

In [27]:
df

,userId,movieId,rating,timestamp,movie_title,genres,hour,day_of_week,movie_rating_count,user_rating_count,movie_avg_rating,preference,userId_encoded,movieId_encoded
0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,18,6,0.652439,0.079401,0.760207,1,0,0
1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance,18,6,0.155488,0.079401,0.613248,1,0,2
2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller,18,6,0.307927,0.079401,0.765795,1,0,5
3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,19,6,0.615854,0.079401,0.772304,1,0,43
4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,18,6,0.618902,0.079401,0.830610,1,0,46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100245,610,166534,4.0,2017-05-03 21:53:22,Split (2017),Drama|Horror|Thriller,21,2,0.015244,0.470787,0.629630,1,609,9133
100246,610,168248,5.0,2017-05-03 22:21:31,John Wick: Chapter Two (2017),Action|Crime|Thriller,22,2,0.018293,0.470787,0.809524,1,609,9160
100247,610,168250,5.0,2017-05-08 19:50:47,Get Out (2017),Horror,19,0,0.042683,0.470787,0.696296,1,609,9161
100248,610,168252,5.0,2017-05-03 21:19:12,Logan (2017),Action|Sci-Fi,21,2,0.073171,0.470787,0.840000,1,609,9162
100249,610,170875,3.0,2017-05-03 21:20:15,The Fate of the Furious (2017),Action|Crime|Drama|Thriller,21,2,0.006098,0.470787,0.407407,1,609,9202

In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SequentialFeatureSelector

In [49]:
X = df.drop(columns=['preference', 'movie_title', 'timestamp','genres','rating','userId','movieId'], errors='ignore')
y = df['preference']

In [50]:
model = LogisticRegression(max_iter=1000)

In [51]:
sfs = SequentialFeatureSelector(
    model,
    n_features_to_select=5,
    direction='forward',
    cv=3   
)

In [52]:
sfs.fit(X, y)

SequentialFeatureSelector(cv=3, estimator=LogisticRegression(max_iter=1000),
                          n_features_to_select=5)

In [53]:
selected_features = X.columns[sfs.get_support()]

print(selected_features)

Index(['hour', 'movie_rating_count', 'user_rating_count', 'movie_avg_rating',
       'movieId_encoded'],
      dtype='object')